apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: eventrunner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: eventrunner-account
      imagePullSecrets:
        - name: ghcr-io-cred
      containers:
        - name: api
          image: ghcr.io/carverauto/eventrunner-api:v0.0.39
          imagePullPolicy: Always
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
          envFrom:
            - configMapRef:
                name: api-config
          volumeMounts:
            - name: config
              mountPath: /app/configs
            - name: nats-creds
              mountPath: /app/nats.creds
              subPath: nats.creds
      volumes:
        - name: config
          configMap:
            name: api-config
        - name: nats-creds
          secret:
            secretName: nats-creds
            items:
              - key: nats.creds
                path: nats.creds