apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-rules-data
  namespace: eventrunner
data:
  rules.json: |
    [
      {
        "id": "oathkeeper-health",
        "upstream": {
          "preserve_host": true,
          "url": "http://oathkeeper-proxy.default.svc.cluster.local:4455"
        },
        "match": {
          "url": "http://oathkeeper-proxy.default.svc.cluster.local:4455/health/alive",
          "methods": ["GET"]
        },
        "authenticators": [
          {
            "handler": "noop"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id": "judge-endpoint",
        "upstream": {
          "preserve_host": true,
          "url": "http://eventrunner-api.eventrunner.svc.cluster.local:8200"
        },
        "match": {
          "url": "http://oathkeeper-proxy.default.svc.cluster.local/judge",
          "methods": ["GET"]
        },
        "authenticators": [
          {
            "handler": "jwt",
            "config": {
              "jwks_urls": ["http://jwks-server.eventrunner.svc.cluster.local/jwks.json"],
              "trusted_issuers": ["https://affectionate-brattain-fl0yahcycw.projects.oryapis.com"],
              "target_audience": ["eventrunner"]
            }
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "header",
            "config": {
              "headers": {
                "X-User": "{{ print .Subject }}",
                "X-Tenant-ID": "{{ print .Extra.tenant_id }}",
                "X-Request-Id": "{{ print .RequestID }}"
              }
            }
          }
        ]
      }
    ]