apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-rules-data
  namespace: eventrunner
data:
  rules.json: |
    [
      {
        "id": "auth-rule",
        "upstream": {
          "preserve_host": true,
          "url": "http://eventrunner-api.eventrunner.svc.cluster.local:8200"
        },
        "match": {
          "url": ".*",
          "methods": ["GET"]
        },
        "authenticators": [
          {
            "handler": "jwt",
            "config": {
              "jwks_urls": ["http://jwks-server.eventrunner.svc.cluster.local/jwks.json"],
              "trusted_issuers": ["https://affectionate-brattain-fl0yahcycw.projects.oryapis.com"],
              "required": false
            }
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "header",
            "config": {
              "headers": {
                "X-User": "{{ print .Subject }}",
                "X-Tenant-ID": "{{ print .Extra.tenant_id }}",
                "X-Request-Id": "{{ print .RequestID }}"
              }
            }
          }
        ]
      }
    ]