apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwks-server
  namespace: eventrunner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwks-server
  template:
    metadata:
      labels:
        app: jwks-server
    spec:
      serviceAccountName: eventrunner-account
      imagePullSecrets:
        - name: ghcr-io-cred
      containers:
        - name: jwks-server
          image: ghcr.io/carverauto/jwks-server:v0.0.01
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /app/configs
      volumes:
        - name: config
          configMap:
            name: eventrunner-config
        - name: nats-creds
          secret:
            secretName: nats-creds
            items:
              - key: nats.creds
                path: nats.creds