apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwks-server
  namespace: eventrunner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwks-server
  template:
    metadata:
      labels:
        app: jwks-server
    spec:
      containers:
        - name: jwks-server
          image: ghcr.io/carverauto/jwks-server:v0.0.03
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: jwks-volume
              mountPath: /app/config/jwks.json
              subPath: jwks.json
            - name: rules-volume
              mountPath: /app/config/rules.json
              subPath: rules.json
      volumes:
        - name: jwks-volume
          configMap:
            name: jwks-data
            items:
              - key: jwks.json
                path: jwks.json
        - name: rules-volume
          configMap:
            name: oathkeeper-rules-data
            items:
              - key: rules.json
                path: rules.json
      imagePullSecrets:
        - name: ghcr-io-cred