apiVersion: v1
kind: Service
metadata:
  name: jwks-server
  namespace: eventrunner
spec:
  selector:
    app: jwks-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP