apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  enable-real-ip: "true"
  proxy-buffer-size: "16k"
  proxy-body-size: "0"
  real-ip-header: "X-Forwarded-For"
  use-forwarded-headers: "true"
  server-snippet: |
    location ~ / {
      internal;
      proxy_pass http://oathkeeper-proxy.default.svc.cluster.local:4455;
      proxy_method $request_method;
      proxy_http_version 1.1;
      proxy_connect_timeout 2s;
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";
      proxy_set_header Host $host;
    
      # Forward the original request information
      proxy_set_header X-Original-URI $request_uri;
      proxy_set_header X-Original-Method $request_method;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host:$server_port;
      proxy_set_header X-Forwarded-Uri $request_uri;
    
      # Keep the Authorization header for the OAuth check
      proxy_set_header Authorization $http_authorization;
    }