apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: ingress-nginx
    meta.helm.sh/release-namespace: ingress-nginx
    metallb.universe.tf/address-pool: k3s-pool
    metallb.universe.tf/allow-shared-ip: "true"
    metallb.universe.tf/ip-allocated-from-pool: k3s-pool
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv6
  - IPv4
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: smtp
    port: 25
    protocol: TCP
    targetPort: 25
  - name: smtps
    port: 465
    protocol: TCP
    targetPort: 465
  - name: submission
    port: 587
    protocol: TCP
    targetPort: 587
  - name: imaps
    port: 993
    protocol: TCP
    targetPort: 993
  sessionAffinity: None
  type: LoadBalancer