apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  repo: https://kubernetes.github.io/ingress-nginx
  chart: ingress-nginx
  targetNamespace: ingress-nginx
  valuesContent: |-
    controller:
      kind: DaemonSet
      service:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/address-pool: k3s-pool
          metallb.universe.tf/allow-shared-ip: "true"
        ipFamilyPolicy: PreferDualStack
        ipFamilies:
          - IPv6
          - IPv4
      config:
        use-forwarded-headers: "true"
      metrics:
        enabled: true
      extraArgs:
        enable-ssl-passthrough: "true"