apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cluster-pg-backup
  namespace: cnpg-system
spec:
  schedule: "0 0 * * *"  # Daily at midnight
  backupOwnerReference: self
  cluster:
    name: cluster-pg
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: cluster-pg-snapshot
  namespace: cnpg-system
spec:
  volumeSnapshotClassName: local-path
  source:
    persistentVolumeClaimName: cluster-pg-1