apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-pg
  namespace: cnpg-system
  labels:
    istio-injection: "disabled"
spec:
  instances: 3

  postgresql:
    parameters:
      shared_buffers: 256MB
      max_connections: "100"
      password_encryption: scram-sha-256

  storage:
    size: 15Gi
    storageClass: local-path

  superuserSecret:
    name: cluster-pg-superuser

  bootstrap:
    initdb:
      # You can choose to create the postgres database only,
      # and then let the operator create the application (kratos) database.
      # Here’s an example to directly create kratos:
      database: kratos
      owner: kratos
      secret:
        name: kratos-db-credentials

  managed:
    roles:
      - name: kratos
        ensure: present
        login: true
        superuser: true
        createdb: true
        createrole: true
        inherit: true
        replication: false
        bypassrls: false

  monitoring:
    enablePodMonitor: true

  env:
    - name: KRATOS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kratos-db-credentials
          key: password  # corrected key name
