apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-rules-data
  namespace: eventrunner
data:
  rules.json: |
    [
      {
        "id": "health-check",
        "match": {
          "url": "<.*>",
          "methods": ["GET"],
          "headers": {
            "X-Original-Uri": ["^/\\.well-known/health$"]
          }
        },
        "authenticators": [
          {
            "handler": "anonymous",
            "config": {
              "subject": "health-check"
            }
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ],
        "upstream": {
          "url": "http://eventrunner-api.eventrunner.svc.cluster.local:8200",
          "preserve_host": true
        }
      }
    ]