apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-rules-data
  namespace: eventrunner
data:
  rules.json: |
    [
        {
          "id": "decisions-endpoint",
          "upstream": {
            "url": "http://oathkeeper-api:4456"
          },
          "match": {
            "url": "http://oathkeeper-proxy/decisions",
            "methods": ["GET"]
          },
          "authenticators": [
            {
              "handler": "noop"
            }
          ],
          "authorizer": {
            "handler": "allow"
          },
          "mutators": [
            {
              "handler": "noop"
            }
          ]
      },
      {
        "id": "api-gateway",
        "upstream": {
          "url": "http://eventrunner-api.eventrunner.svc.cluster.local:8200"
        },
        "match": {
          "url": "http://oathkeeper-proxy.oathkeeper.svc.cluster.local:4455/decisions",
          "methods": ["GET"]
        },
        "authenticators": [
          {
            "handler": "cookie_session",
            "config": {
              "check_session_url": "https://affectionate-brattain-fl0yahcycw.projects.oryapis.com/sessions/whoami",
              "subject_from": "identity.id",
              "extra_from": "@this"
            }
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "header",
            "config": {
              "headers": {
                "X-User-ID": "{{ print .Subject }}"
              }
            }
          }
        ]
      }
    ]