apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-rules
  namespace: eventrunner
data:
  rules.json: |
    [
      {
        "id": "health-check",
        "match": {
          "url": "<^/health/(ready|alive|live)$>",
          "methods": ["GET"]
        },
        "authenticators": [
          {
            "handler": "noop"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ],
        "upstream": {
          "url": "http://eventrunner-api.eventrunner.svc.cluster.local:8200",
          "preserve_host": true
        }
      },
      {
        "id": "well-known",
        "match": {
          "url": "<^/decisions($|/.*)$>",
          "methods": ["GET"]
        },
        "authenticators": [
          {
            "handler": "anonymous"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      }
    ]