apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-rules-data
  namespace: eventrunner
data:
  rules.json: |
    [
      {
        "id": "k8s-health",
        "match": {
          "url": "<^/health/(ready|alive|live)$>",
          "methods": ["GET"]
        },
        "authenticators": [
          {
            "handler": "noop"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ],
        "upstream": {
          "url": "http://oathkeeper-proxy.default.svc.cluster.local:4455"
        }
      },
      {
        "id": "wellknown-endpoints",
        "match": {
          "url": "<^/decisions/.well-known/(alive|health)>",
          "methods": ["GET"]
        },
        "authenticators": [
          {
            "handler": "noop"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ],
        "upstream": {
          "url": "http://eventrunner-api.eventrunner.svc.cluster.local:8200/.well-known/alive",
          "preserve_host": true
        }
      }
    ]