apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-rules-data
  namespace: eventrunner
data:
  rules.json: |
    [
      {
        "id": "health-check",
        "match": {
          "url": "<^http://oathkeeper-proxy\\.default\\.svc\\.cluster\\.local:4455/authenticate$>",
          "methods": [
            "GET"],
          "headers": {
            "X-Original-Uri": [
              "^/\\.well-known/health$"]
          }
        },
        "authenticators": [
          {
            "handler": "anonymous",
            "config": {
              "subject": "guest"
            }
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ],
        "upstream": {
          "url": "http://eventrunner-api.eventrunner.svc.cluster.local:8200/.well-known/health",
          "preserve_host": false,
          "preserve_path": false
        }
      },
      {
        "id": "alive-check",
        "match": {
          "url": "<^http://oathkeeper-proxy\\.default\\.svc\\.cluster\\.local:4455/authenticate$>",
          "methods": [
            "GET"],
          "headers": {
            "X-Original-Uri": [
              "^/\\.well-known/alive$"]
          }
        },
        "authenticators": [
          {
            "handler": "anonymous",
            "config": {
              "subject": "guest"
            }
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ],
        "upstream": {
          "url": "http://eventrunner-api.eventrunner.svc.cluster.local:8200/.well-known/alive",
          "preserve_host": false,
          "preserve_path": false
        }
      }
    ]
