apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-rules-data
  namespace: eventrunner
data:
  rules.json: |
    [
      {
        "id": "api-health-check",
        "match": {
          "url": "<.*>",
          "methods": [
            "GET"],
          "headers": {
            "x-auth-request-redirect": [
              "/api/v1/health"]
          }
        },
        "authenticators": [
          {
            "handler": "anonymous",
            "config": {
              "subject": "guest"
            }
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "header",
            "config": {
              "headers": {
                "X-User": "anonymous",
                "X-Tenant-ID": "default",
                "X-Request-Id": "{{ index .Header \"x-request-id\" }}"
              }
            }
          }
        ],
        "upstream": {
          "preserve_host": true,
          "url": "http://eventrunner-api.eventrunner.svc.cluster.local:8200",
          "strip_path": "/judge"
        }
      }
    ]