apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-rules-data
  namespace: eventrunner
data:
  rules.json: |
    [
        {
          "id": "decisions-endpoint",
          "upstream": {
            "url": "http://oathkeeper-api.oathkeeper.svc.cluster.local:4456"
          },
          "match": {
            "url": "http://oathkeeper-proxy.oathkeeper.svc.cluster.local/decisions",
            "methods": ["GET"]
          },
          "authenticators": [
            {
              "handler": "noop"
            }
          ],
          "authorizer": {
            "handler": "allow"
          },
          "mutators": [
            {
              "handler": "noop"
            }
          ]
      },
      {
        "id": "eventrunner-api",
        "upstream": {
          "url": "http://eventrunner-api.eventrunner.svc.cluster.local:8200",
          "preserve_host": true
        },
        "match": {
          "url": "http://api.tunnel.threadr.ai/<.*>",
          "methods": ["GET", "POST", "PUT", "DELETE"]
        },
        "authenticators": [
          {
            "handler": "oauth2_introspection",
            "config": {
              "introspection_url": "https://affectionate-brattain-fl0yahcycw.projects.oryapis.com/admin/oauth2/introspect",
              "scope_strategy": "exact",
              "required_scope": ["api:access"]
            }
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "header",
            "config": {
              "headers": {
                "X-User": "{{ print .Subject }}",
                "X-Tenant-ID": "{{ print .Extra.tenant_id }}"
              }
            }
          }
        ],
        "errors": [
          {
            "handler": "json"
          }
        ]
      }
    ]