apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mail-tls-certificate-rsa
  namespace: default
spec:
  secretName: mail-tls-certificate-rsa
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames: [mail.tunnel.threadr.ai]
  issuerRef:
    name: threadr-issuer
    kind: ClusterIssuer
