apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mailserver
  namespace: default
spec:
  serviceName: mailserver
  replicas: 1
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      labels:
        app: mailserver
    spec:
      containers:
        - name: mailserver
          image: ghcr.io/docker-mailserver/docker-mailserver:latest
          ports:
            - containerPort: 25   # SMTP
              name: smtp
            - containerPort: 465  # SMTPS
              name: smtps
            - containerPort: 587  # Submission
              name: submission
            - containerPort: 993  # IMAPS
              name: imaps
          volumeMounts:
            - name: maildata
              mountPath: /var/mail
            - name: mailstate
              mountPath: /var/mail-state
            - name: mailconfig
              mountPath: /tmp/docker-mailserver
            - name: certs
              mountPath: /etc/letsencrypt/live/mail.tunnel.threadr.ai
              readOnly: true
          envFrom:
            - configMapRef:
                name: mailserver-config
      volumes:
        - name: certs
          secret:
            secretName: mail-tls-secret
  volumeClaimTemplates:
    - metadata:
        name: maildata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-path
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: mailstate
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: mailconfig
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi