apiVersion: v1
kind: ConfigMap
metadata:
  name: mailserver-config
  namespace: default
data:
  .env: |
    # General
    OVERRIDE_HOSTNAME=mail.tunnel.threadr.ai
    POSTMASTER_ADDRESS=postmaster@tunnel.threadr.ai
    POSTSCREEN_ACTION=enforce
    ONE_DIR=1
    ENABLE_CLAMAV=0
    ENABLE_SPAMASSASSIN=1
    SPAMASSASSIN_SPAM_TO_INBOX=1
    ENABLE_FAIL2BAN=1
    SSL_TYPE=manual
    
    # IPv6 settings
    NETWORK_INTERFACE=eth0
    PERMIT_DOCKER=connected-networks
    POSTFIX_INET_PROTOCOLS=all
    
    # Debug
    LOG_LEVEL=debug