apiVersion: v1
kind: ConfigMap
metadata:
  name: mailserver-config
  namespace: default
data:
  .env: |
    # General
    OVERRIDE_HOSTNAME=mail.tunnel.threadr.ai
    POSTMASTER_ADDRESS=postmaster@tunnel.threadr.ai
    POSTSCREEN_ACTION=ignore
    ONE_DIR=1
    ENABLE_CLAMAV=0
    ENABLE_SPAMASSASSIN=1
    SPAMASSASSIN_SPAM_TO_INBOX=1
    ENABLE_FAIL2BAN=1
    SSL_TYPE=manual
    
    # IPv6 settings
    NETWORK_INTERFACE=eth0
    #PERMIT_DOCKER=connected-networks
    POSTFIX_INET_PROTOCOLS=all
    
    #PERMIT_DOCKER=host
    #PERMIT_DOCKER=all
    PERMIT_DOCKER=none
    
    #POSTFIX_MYNETWORKS=2001:470:c0b5:5::0/64, 2001:470:c0b5:4::0/64, 2001:470:c0b5:2::0/64
    POSTFIX_MYNETWORKS=10.0.0.0/8, 2001:470:c0b5:5::0/64, 2001:470:c0b5:4::0/64, 2001:470:c0b5:2::0/64
    POSTSCREEN_UPSTREAM_PROXY_PROTOCOL=haproxy
    POSTFIX_SUBMISSION_SMTPD_UPSTREAM_PROXY_PROTOCOL=haproxy
    POSTFIX_SUBMISSIONS_SMTPD_UPSTREAM_PROXY_PROTOCOL=haproxy
    ENABLE_POSTFIX_VIRTUAL_TRANSPORT=1
    
    DOVECOT_HAPROXY_TRUSTED_NETWORKS=10.0.0.0/8
    DOVECOT_INET_PROTOCOLS=all

    # Debug
    LOG_LEVEL=trace