apiVersion: v1
kind: Service
metadata:
  name: mailserver
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "mail.tunnel.threadr.ai"
    metallb.universe.tf/address-pool: k3s-pool
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv6
    - IPv4
  ports:
    - port: 25
      name: smtp
      targetPort: smtp
    - port: 465
      name: smtps
      targetPort: smtps
    - port: 587
      name: submission
      targetPort: submission
    - port: 993
      name: imaps
      targetPort: imaps
  selector:
    app: mailserver