apiVersion: v1
kind: ConfigMap
metadata:
  name: eventrunner-config
  namespace: eventrunner
data:
  .env: |
    APP_NAME=eventrunner
    HTTP_PORT=8200
    LOG_LEVEL=DEBUG
    PUBSUB_BACKEND=NATS
    PUBSUB_BROKER=nats://connect.ngs.global
    NATS_STREAM=eventrunner
    NATS_SUBJECTS=events.products,events.order-logs
    NATS_CREDS_FILE=/app/nats.creds
    NATS_CONSUMER=events
    NATS_MAX_WAIT=30s
    NATS_MAX_PULL_WAIT=10
    NATS_BATCH_SIZE=100
    CASSANDRA_HOSTS=scylla-client.scylla.svc.cluster.local:9042
    CASSANDRA_USERNAME=cassandra
    CASSANDRA_PASSWORD=cassandra
    CASSANDRA_KEYSPACE=eventrunner
    APP_ENV=staging
  .staging.env: |
    LOG_LEVEL=DEBUG