apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-scylla-us-east-1-us-east-1a-0
  namespace: scylla
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
