datacenter: us-east-1
racks:
  - name: us-east-1a
    members: 1
    storage:
      capacity: 24Ti
      storageClassName: scylladb-local-xfs
    nodeSelector:
      scylla-ready: "true"
    resources:
      limits:
        cpu: 16
        memory: 32Gi
      requests:
        cpu: 1
        memory: 4Gi
  - name: us-east-1b
    members: 1
    storage:
      capacity: 24Ti
      storageClassName: scylladb-local-xfs
    nodeSelector:
      scylla-ready: "true"
    resources:
      limits:
        cpu: 16
        memory: 32Gi
      requests:
        cpu: 1
        memory: 4Gi
  - name: us-east-1c
    members: 1
    storage:
      capacity: 24Ti
      storageClassName: scylladb-local-xfs
    nodeSelector:
      scylla-ready: "true"
    resources:
      limits:
        cpu: 16
        memory: 32Gi
      requests:
        cpu: 1
        memory: 4Gi

# Apply kernel settings for better ScyllaDB performance
sysctls:
  - "fs.aio-max-nr=2097152"
  - "vm.max_map_count=1048575"
  - "net.core.somaxconn=65535"

# Scylla image
scyllaImage:
  repository: scylladb/scylla
  tag: 6.2.3
  pullPolicy: Always

agentImage:
  repository: scylladb/scylla-manager-agent
  tag: 3.4.0
  pullPolicy: Always

# Add image pull secrets if needed
imagePullSecrets:
  - name: regcred

# Add security context for file descriptor limits
securityContext:
  privileged: true
  capabilities:
    add: [ "SYS_ADMIN", "SYS_RESOURCE" ]
  runAsUser: 0  # Run as root
  fsGroup: 0

# Add resource limits for file descriptors
resources:
  limits:
    nofile: 1048576

serviceAccount:
  name: scylla-privileged
  create: false

serviceMonitor:
  create: true