apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: default  # Use the profile that matches your installation
  meshConfig:
    extensionProviders:
    - name: "ext-authz"
      envoyExtAuthzHttp:
        service: "oathkeeper-api.auth.svc.cluster.local"
        port: 4456
        timeout: 10s
        failOpen: false
        statusOnError: "500"
        pathPrefix: /decisions
        includeRequestHeadersInCheck: ["authorization"]

