apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-tls
  namespace: mongo
spec:
  secretName: mongodb-tls-secret
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiration
  issuerRef:
    kind: ClusterIssuer
    name: carverauto-issuer
  commonName: mongodb.tunnel.carverauto.dev
  dnsNames:
    - mongodb.tunnel.carverauto.dev
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
