tls:
  enabled: true
  mode: "requireTLS"
  ca:
    secret:
      secretName: "mongodb-tls-secret"
      key: "ca.crt"
  cert:
    secret:
      secretName: "mongodb-tls-secret"
      key: "tls.crt"
  key:
    secret:
      secretName: "mongodb-tls-secret"
      key: "tls.key"

auth:
  enabled: true
  x509:
    enabled: true

service:
  type: LoadBalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "mongodb.tunnel.threadr.ai"
    metallb.universe.tf/address-pool: k3s-pool
    metallb.universe.tf/allow-shared-ip: "true"
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv6
    - IPv4
  clusterIP: "2001:470:c0b5:5::7620"  # Added explicit IPv6 cluster IP
  clusterIPs:
    - "2001:470:c0b5:5::7620"  # Primary IPv6
    - 10.43.114.105  # Secondary IPv4 (using your existing one)
  externalTrafficPolicy: Cluster
  port: 27017