auth:
  enabled: true
  existingSecret: mongodb-auth-secret
  replicaSetKey: mongodb-replica-set-secret

tls:
  enabled: true
  mode: requireTLS
  existingSecret: mongodb-tls-secret
  caCert:
    existingSecret: mongodb-ca-cert-secret
    key: mongodb-ca-cert

volumeMounts:
  - name: certs-volume
    mountPath: /certs
    readOnly: true

volumes:
  - name: certs-volume
    secret:
      secretName: mongodb-ca-cert-secret
      items:
        - key: mongodb-ca-cert
          path: mongodb-ca-cert