scylla:
  datacenter: us-east-1
  racks:
    - name: us-east-1a
      members: 4
      storage:
        capacity: 10Gi
        storageClassName: local-path
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi
spec:
  sysctls:
    - "fs.aio-max-nr=2097152"
