version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:16.13.1
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - kratos-selfservice-ui-node-{{ checksum "package-lock.json" }}
      - run: npm ci --legacy-peer-deps
      - save_cache:
          paths:
            - node_modules
          key: kratos-selfservice-ui-node-{{ checksum "package-lock.json" }}
      - run: npm test

  build:
    docker:
      - image: circleci/node:16.13.1
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - kratos-selfservice-ui-node-{{ checksum "package-lock.json" }}
      - run: npm ci --legacy-peer-deps
      - save_cache:
          paths:
            - node_modules
          key: kratos-selfservice-ui-node-{{ checksum "package-lock.json" }}
      - run: npm run build

  release:
    docker:
      - image: cimg/base:stable
    environment:
      DOCKER_BUILDKIT: 1
      DOCKER_CLI_EXPERIMENTAL: enabled
      BUILDX_PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
    working_directory: ~/app
    steps:
      - checkout
      - run:
          command: |
            echo 'export DOCKER_FULL_TAG=$(echo $CIRCLE_TAG | tr '+' '_')' >> $BASH_ENV
            echo 'export DOCKER_SHORT_TAG=$(echo $CIRCLE_TAG | cut -d '+' -f1)' >> $BASH_ENV
            ./.circleci/release_name.bash
            source $BASH_ENV
      - setup_remote_docker
      - run:
          name: Set up Docker Buildx
          command: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker buildx create --name multiarch-builder --use
      - run:
          docker login --username "$DOCKER_USERNAME" --password
          "$DOCKER_PASSWORD"
      - run:
          docker buildx build --platform $BUILDX_PLATFORMS -t
          oryd/kratos-selfservice-ui-node:latest -t
          oryd/kratos-selfservice-ui-node:$DOCKER_SHORT_TAG --push .

workflows:
  tbr:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - test
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
