oathkeeper:
  config:
    serve:
      proxy:
        port: 4455
        cors:
          enabled: true
          allowed_origins:
            - "*"
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
          allowed_headers:
            - Authorization
            - Content-Type
            - X-Debug
          exposed_headers:
            - X-User
            - X-Tenant-ID
            - X-Request-Id
          allow_credentials: true
          debug: true
      api:
        port: 4456

    access_rules:
      repositories:
        - "http://auth-server.eventrunner.svc.cluster.local/rules.json"
      matching_strategy: regexp

    authenticators:
      anonymous:
        enabled: true
        config:
          subject: "guest"
      noop:
        enabled: true

    authorizers:
      allow:
        enabled: true
      deny:
        enabled: true

    errors:
      fallback:
        - json
      handlers:
        json:
          enabled: true
          config:
            verbose: true

    mutators:
      noop:
        enabled: true
      header:
        enabled: true
        config:
          headers: {}

    log:
      level: debug
      format: json