oathkeeper:
  config:
    serve:
      proxy:
        port: 4455
        cors:
          enabled: true
      api:
        port: 4456
        cors:
          enabled: true

    access_rules:
      repositories:
        - inline://WwogIHsKICAgICJpZCI6ICJoZWFsdGgtcmVhZGluZXNzIiwKICAgICJtYXRjaCI6IHsKICAgICAgInVybCI6ICJodHRwOi8vMTI3LjAuMC4xOjQ0NTYvaGVhbHRoLyoiLAogICAgICAibWV0aG9kcyI6IFsKICAgICAgICAiR0VUIgogICAgICBdCiAgICB9LAogICAgImF1dGhlbnRpY2F0b3JzIjogWwogICAgICB7CiAgICAgICAgImhhbmRsZXIiOiAiYW5vbnltb3VzIgogICAgICB9CiAgICBdLAogICAgImF1dGhvcml6ZXIiOiB7CiAgICAgICJoYW5kbGVyIjogImFsbG93IgogICAgfSwKICAgICJtdXRhdG9ycyI6IFsKICAgICAgewogICAgICAgICJoYW5kbGVyIjogIm5vb3AiCiAgICAgIH0KICAgIF0KICB9LAogIHsKICAgICJpZCI6ICJkZWZhdWx0IiwKICAgICJtYXRjaCI6IHsKICAgICAgInVybCI6ICJodHRwOi8vMTI3LjAuMC4xOjQ0NTYvKiIsCiAgICAgICJtZXRob2RzIjogWwogICAgICAgICJHRVQiCiAgICAgIF0KICAgIH0sCiAgICAiYXV0aGVudGljYXRvcnMiOiBbCiAgICAgIHsKICAgICAgICAiaGFuZGxlciI6ICJhbm9ueW1vdXMiCiAgICAgIH0KICAgIF0sCiAgICAiYXV0aG9yaXplciI6IHsKICAgICAgImhhbmRsZXIiOiAiYWxsb3ciCiAgICB9LAogICAgIm11dGF0b3JzIjogWwogICAgICB7CiAgICAgICAgImhhbmRsZXIiOiAibm9vcCIKICAgICAgfQogICAgXQogIH0KXQ==
      matching_strategy: glob

    authenticators:
      anonymous:
        enabled: true
        config:
          subject: guest
      noop:
        enabled: true
      jwt:
        enabled: true
        config:
          jwks_urls:
            - http://jwks-server.eventrunner.svc.cluster.local/jwks.json

    authorizers:
      allow:
        enabled: true

    mutators:
      noop:
        enabled: true
      id_token:
        enabled: true
        config:
          issuer_url: "https://affectionate-brattain-fl0yahcycw.projects.oryapis.com"
          jwks_url: http://jwks-server.eventrunner.svc.cluster.local/jwks.json
          ttl: "15m"

  deployment:
    replicas: 1
    pod:
      containers:
        - name: oathkeeper
          image: oryd/oathkeeper:v0.40.7
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 4456
            failureThreshold: 3
            periodSeconds: 10
            initialDelaySeconds: 5
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /health/alive
              port: 4456
            failureThreshold: 3
            periodSeconds: 10
            initialDelaySeconds: 5
            timeoutSeconds: 1