oathkeeper:
  config:
    serve:
      proxy:
        port: 4455
        cors:
          enabled: true
          allowed_origins:
            - "*"
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
          allowed_headers:
            - Authorization
            - Content-Type
          exposed_headers:
            - X-User
            - X-Tenant-ID
            - X-Request-Id
          allow_credentials: true
          debug: true
      api:
        port: 4456
        cors:
          enabled: true

    access_rules:
      repositories:
        - "http://auth-server.eventrunner.svc.cluster.local/rules.json"
      matching_strategy: glob

    authenticators:
      anonymous:
        enabled: true
        config:
          subject: guest
      noop:
        enabled: true
      jwt:
        enabled: true
        config:
          jwks_urls:
            - "https://affectionate-brattain-fl0yahcycw.projects.oryapis.com/.well-known/jwks.json"

    authorizers:
      allow:
        enabled: true

    mutators:
      noop:
        enabled: true
      header:
        config:
          headers: {} # This is important - we're enabling header mutator with empty default config
        enabled: true

    log:
      level: debug
      format: json

  deployment:
    replicas: 1
    pod:
      containers:
        - name: oathkeeper
          image: oryd/oathkeeper:v0.40.7
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 4456
            failureThreshold: 3
            periodSeconds: 10
            initialDelaySeconds: 5
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /health/alive
              port: 4456
            failureThreshold: 3
            periodSeconds: 10
            initialDelaySeconds: 5
            timeoutSeconds: 1