---
apiVersion: v1
kind: Service
metadata:
  name: oathkeeper-proxy
  namespace: default
  labels:
    app.kubernetes.io/name: oathkeeper
spec:
  ports:
    - name: proxy
      port: 4455
      targetPort: 4455
  selector:
    app.kubernetes.io/name: oathkeeper
---
apiVersion: v1
kind: Service
metadata:
  name: oathkeeper-api
  namespace: default
  labels:
    app.kubernetes.io/name: oathkeeper
spec:
  ports:
    - name: api
      port: 4456
      targetPort: 4456
  selector:
    app.kubernetes.io/name: oathkeeper