apiVersion: v1
kind: Service
metadata:
  name: goflow2
  namespace: netflow
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "goflow2.tunnel.threadr.ai"
    metallb.universe.tf/address-pool: k3s-pool
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: sflow
      port: 6343
      targetPort: sflow
      protocol: UDP
    - name: netflow
      port: 2055
      targetPort: netflow
      protocol: UDP
  selector:
    app: goflow2
