apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-admin
  namespace: eventrunner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-admin
  template:
    metadata:
      labels:
        app: api-admin
    spec:
      serviceAccountName: eventrunner-account
      imagePullSecrets:
        - name: ghcr-io-cred
      containers:
        - name: api-admin
          image: ghcr.io/carverauto/api-admin:v0.0.05
          imagePullPolicy: Always
          env:
            - name: DSN
              value: "mongodb://er-mongodb.mongo.svc.cluster.local:27017"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: ORY_SDK_URL
              value: "http://hydra-admin.auth:4445"
          envFrom:
            - configMapRef:
                name: api-admin-config
          volumeMounts:
            - name: config
              mountPath: /app/configs
            - name: nats-creds
              mountPath: /app/nats.creds
              subPath: nats.creds
      volumes:
        - name: config
          configMap:
            name: api-admin-config
        - name: nats-creds
          secret:
            secretName: nats-creds
            items:
              - key: nats.creds
                path: nats.creds