apiVersion: v1
kind: Service
metadata:
  name: external-dns-test
  annotations:
    external-dns.alpha.kubernetes.io/hostname: test.tunnel.threadr.ai
spec:
  type: LoadBalancer
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

