apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Debug
  nodeToNodeMeshEnabled: true
  asNumber: 65000
  serviceClusterIPs:
    - cidr: 10.43.0.0/16
    - cidr: "2001:470:c0b5:5::/64"
  serviceLoadBalancerIPs:
    - cidr: "10.43.0.0/16"
    - cidr: "2001:470:c0b5:5::/64"
