apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: default-ipv6-ippool
spec:
  cidr: 2001:470:c0b5:4::/64
  ipipMode: Never
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Never
  allowedUses:
    - Workload
    - Tunnel
  disableBGPExport: false
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: default-ipv4-ippool-16
spec:
  cidr: 10.44.0.0/16
  ipipMode: Never
  vxlanMode: Never
  natOutgoing: true
  nodeSelector: all()
  disabled: false