apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-services-tls
  namespace: auth
  labels:
    app.kubernetes.io/name: auth-services
spec:
  secretName: auth-services-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiration
  issuerRef:
    kind: ClusterIssuer
    name: carverauto-issuer
  commonName: "*.tunnel.carverauto.dev"
  dnsNames:
    - "*.tunnel.carverauto.dev"
  usages:
    - digital signature
    - key encipherment
    - server auth