apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-grafana-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "threadr-issuer"
    external-dns.alpha.kubernetes.io/hostname: "prometheus.tunnel.threadr.ai,grafana.tunnel.threadr.ai"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: prometheus.tunnel.threadr.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: promstack-kube-prometheus-prometheus
                port:
                  number: 9090
    - host: grafana.tunnel.threadr.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: promstack-grafana
                port:
                  number: 80
  tls:
    - hosts:
        - prometheus.tunnel.threadr.ai
        - grafana.tunnel.threadr.ai
      secretName: prometheus-grafana-tls  # Let cert-manager manage this secret
