nameOverride: "promstack"
fullnameOverride: "promstack"

grafana:
  enabled: true

  # Admin credentials
  adminUser: admin
  adminPassword: admin@123

  # SMTP Secret Reference
  smtp:
    enabled: true
    existingSecret: "grafana-secret"
    userKey: "smtp_username"
    passwordKey: "smtp_password"

  # SMTP Configuration
  grafana.ini:
    smtp:
      enabled: true
      host: mail.tunnel.threadr.ai:25
      from_address: grafana@tunnel.threadr.ai
      from_name: Grafana
      startTLS_policy: NoStartTLS
      skip_verify: true

  # Service configuration
  service:
    name: promstack-grafana
    port: 80

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}

  service:
    name: promstack-kube-prometheus-prometheus
    port: 9090

additionalServiceMonitors:
  - name: cloudnative-pg
    selector:
      matchLabels:
        postgresql: cloudnative-pg
    namespaceSelector:
      matchNames:
        - cnpg-system
    endpoints:
      - port: metrics
        interval: 30s