apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: dns
data:
  Corefile: |
    cert.tunnel.threadr.ai:53 {
      file /etc/coredns/zones/cert.tunnel.threadr.ai.db
      log
      errors
      prometheus :9153
      cache 30
    }