# Create a dedicated pool for the second nameserver
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dns-ns2-pool
  namespace: metallb-system
  labels:
    dns-server: "ns2"
spec:
  addresses:
    - 2001:470:c0b5:5::4/128  # Second nameserver IPv6