apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventrunner-api
  namespace: eventrunner
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://oathkeeper-proxy.default.svc.cluster.local:4455/decisions"
    nginx.ingress.kubernetes.io/auth-signin: "https://affectionate-brattain-fl0yahcycw.projects.oryapis.com/ui/login"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-User,X-Tenant-ID,X-Roles,X-Request-Id"
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header Authorization $http_authorization;
      proxy_set_header Content-Length "";
      proxy_set_header Host $host;
      
      # Forward the original request information
      proxy_set_header X-Original-URI $request_uri;
      proxy_set_header X-Original-Method $request_method;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  ingressClassName: nginx
  rules:
    - host: api.tunnel.threadr.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eventrunner-api
                port:
                  number: 8200