apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eventrunner
resources:
  - istio-auth-policy.yaml
  - istio-mesh-config.yaml
  - eventrunner.yaml
  - configmap.yaml
  - service.yaml
  - ingress.yaml
  - health-alive-ingress.yaml
  - service-proxy.yaml