apiVersion: metallb.io/v1beta1
kind: BGPPeer
metadata:
  name: router-peer
  namespace: metallb-system
spec:
  myASN: 65001
  peerASN: 65000
  peerAddress: 192.168.2.1
---
apiVersion: metallb.io/v1beta1
kind: BGPPeer
metadata:
  name: router-peer-ipv6
  namespace: metallb-system
spec:
  myASN: 65001
  peerASN: 65000
  peerAddress: 2001:470:c0b5:2::1
---
apiVersion: metallb.io/v1beta1
kind: BGPPeer
metadata:
  name: router-peer
  namespace: metallb-system
spec:
  myASN: 65001
  peerASN: 65000
  peerAddress: 192.168.1.1