apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spire-ca
  namespace: spire
spec:
  secretName: spire-ca-key-pair
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  commonName: "spire.tunnel.carverauto.dev"
  dnsNames:
    - "spire.tunnel.carverauto.dev"
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  issuerRef:
    name: carverauto-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-ca
  namespace: spire
data:
  ca.crt: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-ca-sync
  namespace: spire
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "update"]
  resourceNames: ["cert-manager-ca"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-ca-sync
  namespace: spire
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
roleRef:
  kind: Role
  name: cert-manager-ca-sync
  apiGroup: rbac.authorization.k8s.io
