apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spire-server
  namespace: spire
  labels:
    app: spire-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spire-server
  serviceName: spire-server
  template:
    metadata:
      namespace: spire
      labels:
        app: spire-server
    spec:
      serviceAccountName: spire-server
      initContainers:
        - name: init-config
          image: busybox
          command: ['sh', '-c']
          args:
            - |
              cp /config-template/server.conf /config/server.conf
              sed -i "s|__DB_PASSWORD__|$DB_PASSWORD|g" /config/server.conf
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spire-postgres
                  key: DB_PASSWORD
          volumeMounts:
            - name: spire-config-template
              mountPath: /config-template
            - name: generated-config
              mountPath: /config
      containers:
        - name: spire-server
          image: ghcr.io/spiffe/spire-server:1.5.1
          args:
            - -config
            - /run/spire/config/server.conf
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: generated-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-data
              mountPath: /run/spire/data
              readOnly: false
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: spire-config-template
          configMap:
            name: spire-server
        - name: generated-config
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: spire-data
        namespace: spire
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi