apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-server
  namespace: spire
data:
  server.conf: |
    server {
      bind_address = "0.0.0.0"
      bind_port = "8081"
      socket_path = "/tmp/spire-server/private/api.sock"
      trust_domain = "tunnel.carverauto.dev"
      data_dir = "/run/spire/data"
      log_level = "DEBUG"
      #AWS requires the use of RSA.  EC cryptography is not supported
      ca_key_type = "rsa-2048"

      ca_subject = {
        country = ["US"],
        organization = ["Carver Automation Corporation"],
        common_name = "tunnel.carverauto.dev",
      }
    }

    plugins {
      DataStore "sql" {
        plugin_data {
          database_type = "postgres"
          connection_string = "dbname=spire user=spire password=__DB_PASSWORD__ host=cluster-pg-rw.cnpg-system.svc.cluster.local port=5432 sslmode=disable"
        }
      }

      UpstreamAuthority "cert-manager" {
        plugin_data {
          issuer_name = "spire-intermediate-issuer"
          issuer_kind = "Issuer"
          issuer_group = "cert-manager.io"
          namespace = "spire"
          ca_bundle_path = "/etc/cert-manager/ca/ca.crt"
        }
      }
    
      NodeAttestor "k8s_sat" {
        plugin_data {
          clusters = {
            # NOTE: Change this to your cluster name
            "carverauto-cluster" = {
              use_token_review_api_validation = true
              service_account_allow_list = ["spire:spire-agent"]
            }
          }
        }
      }

      KeyManager "disk" {
        plugin_data {
          keys_path = "/run/spire/data/keys.json"
        }
      }

      Notifier "k8sbundle" {
        plugin_data {
          namespace = "spire"
          config_map = "spire-bundle"
        }
      }
    }

    health_checks {
      listener_enabled = true
      bind_address = "0.0.0.0"
      bind_port = "8080"
      live_path = "/live"
      ready_path = "/ready"
    }
