# First create an intermediate certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spire-intermediate-ca
  namespace: spire
spec:
  isCA: true
  commonName: "Spire Intermediate CA"
  secretName: spire-intermediate-ca
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  dnsNames:
    - "spire.tunnel.carverauto.dev"
  issuerRef:
    name: spire-root-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# Then create an issuer using the intermediate certificate
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: spire-intermediate-issuer
  namespace: spire
spec:
  ca:
    secretName: spire-intermediate-ca